### ISSUE TITLE
Keypair creation failing with 'str' object has no attribute 'id' error

### ISSUE THREAD

**Issue by BharatKumarK** [cloudify-cosmo/cloudify-openstack-plugin#220]
Keypair creation is failing with below error:
> Task failed 'nova_plugin.keypair.create' -> 'str' object has no attribute 'id'

This is due to incorrect order of parameter passing to the method **set_openstack_runtime_properties**. (See below line...)
https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/master/nova_plugin/keypair.py#L72

**set_openstack_runtime_properties** method definition:
https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/master/openstack_plugin_common/__init__.py#L550

**node template definition:**
node_templates:
  keypair:
    type: cloudify.openstack.nodes.KeyPair
    properties:
      private_key_path: { get_input: private_key_path }
      use_external_resource: true
      create_if_missing: true
      resource_id: { get_input: keypair_name }
      openstack_config: *openstack_config

**Complete execution log:**
[root@cloudify-manager43 f5-usecase-blueprints]# cfy execution start install -d keypair_create_test
Executing workflow install on deployment keypair_create_test [timeout=900 seconds]
2018-03-20 17:19:24.787  CFY <keypair_create_test> Starting 'install' workflow execution
2018-03-20 17:19:25.911  CFY <keypair_create_test> [keypair_at4bsp] Creating node
2018-03-20 17:19:25.911  CFY <keypair_create_test> [keypair_at4bsp.create] Sending task 'nova_plugin.keypair.create'
2018-03-20 17:19:25.911  CFY <keypair_create_test> [keypair_at4bsp.create] Task started 'nova_plugin.keypair.create'
2018-03-20 17:19:28.341  CFY <keypair_create_test> [keypair_at4bsp.create] Task failed 'nova_plugin.keypair.create' -> 'str' object has no attribute 'id'
2018-03-20 17:19:43.453  CFY <keypair_create_test> [keypair_at4bsp.create] Sending task 'nova_plugin.keypair.create' [retry 1/60]
2018-03-20 17:19:43.920  CFY <keypair_create_test> [keypair_at4bsp.create] Task started 'nova_plugin.keypair.create' [retry 1/60]
2018-03-20 17:19:46.053  LOG <keypair_create_test> [keypair_at4bsp.create] INFO: Using external resource keypair: keypair_for_monitoring1
2018-03-20 17:19:45.990  CFY <keypair_create_test> [keypair_at4bsp.create] Task failed 'nova_plugin.keypair.create' -> Failed to use external keypair (node keypair): the public key keypair_for_monitoring1 is available on Openstack, but the private key could not be found at /tmp/keypair_for_monitoring.pem [retry 1/60]
Execution ended, waiting 3 seconds for additional log messages
2018-03-20 17:19:46.924  CFY <keypair_create_test> 'install' workflow execution failed: RuntimeError: Workflow failed: Task failed 'nova_plugin.keypair.create' -> Failed to use external keypair (node keypair): the public key keypair_for_monitoring1 is available on Openstack, but the private key could not be found at /tmp/keypair_for_monitoring.pem
Execution of workflow install for deployment keypair_create_test failed. [error=Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 519, in _remote_workflow_child_thread
    workflow_result = self._execute_workflow_function()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 550, in _execute_workflow_function
    result = self.func(*self.args, **self.kwargs)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/workflows.py", line 27, in install
    node_instances=set(ctx.node_instances))
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 28, in install_node_instances
    processor.install()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 93, in install
    graph_finisher_func=self._finish_install)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/plugins/lifecycle.py", line 114, in _process_node_instances
    self.graph.execute()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 133, in execute
    self._handle_terminated_task(task)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks_graph.py", line 207, in _handle_terminated_task
    raise RuntimeError(message)
RuntimeError: Workflow failed: Task failed 'nova_plugin.keypair.create' -> Failed to use external keypair (node keypair): the public key keypair_for_monitoring1 is available on Openstack, but the private key could not be found at /tmp/keypair_for_monitoring.pem
]
* Run 'cfy events list -e 78f16ce2-108e-4d78-8bbe-ef7da7a451f5' to retrieve the execution's events/logs

**Comment by BharatKumarK** [comment]
Corrected the order and raised pull request: https://github.com/cloudify-cosmo/cloudify-openstack-plugin/pull/221
